### ISSUE TITLE
Menu inicial y de pausa

### ISSUE THREAD

**Issue by carolinajimenez26** [jdiegoh3/gameproyect_pygame#3]
Requisitos (qué deben tener):
### Menu ppal:

-Inicio
-Tutorial
-Salir
### Pausa

-Configurar teclado
-Continuar
-Salir (debe volver al menu ppal)

**Comment by carolinajimenez26** [comment]
¿Cuando se configura el teclado se debería escribir en un archivo de texto?
¿Cada cuánto se debería leer dicho archivo entonces?

---> Buscar solución

**Comment by jdiegoh3** [comment]
Lee las teclas cada que se abre el menu se ejecuta.

-Las te las se guardaran en un archivo de texto.

> La configuracion de teclas siempre debe estar en el menu principal y en el menu de pausa (ambos)
> 
> Nota:Falta ver si las teclas se pueden importar de esa forma

*Asignado a mi , yo me encargo de solucionar el problema

**Comment by carolinajimenez26** [comment]
¿se pueden cambiar las teclas en medio del juego?

**Comment by jdiegoh3** [comment]
Sí , ahi acabé de editar. 
la carga de teclas se hará en ambos casos
